### ISSUE TITLE
about the pre-trained word2vec models

### ISSUE THREAD

**Issue by junxu-ai** [ddhruvkr/Edit-Unsup-TS#1]
Hi,

It seems that the pre-trained word2vec model from [[here](https://drive.google.com/drive/folders/1We3YeS6O9iReXvcxG4XKx0pMO6bIggUR?usp=sharing)]has no wv.vectors.npy, when using word2vec.load().

Thanks！

**Comment by ddhruvkr** [comment]
Hi,

This is because we use two word2vec vectors. The first is that we trained on our dataset (that you downloaded) and the second is the pretrained one that we get from gensim (word2vec-google-news-300). So the error might be in the gensim one.

**Comment by ddhruvkr** [comment]
I just noticed, the "word2vec.model.wv.vectors.npy" was missing from the drive. I have added that. Let me know if it resolves your issue.
