### ISSUE TITLE
wiki.full.aner.ori.train.src file not found

### ISSUE THREAD

**Issue by scott2b** [ddhruvkr/Edit-Unsup-TS#3]
Working my way through trying to get main.py to run. Reached this error. The file in question is not available in the downloads listed in the README

```
FileNotFoundError: [Errno 2] No such file or directory: '../data-simplification/wikilarge/wiki.full.aner.ori.train.src'
```

**Comment by ddhruvkr** [comment]
This is the Wikilarge dataset which you get from https://github.com/XingxingZhang/dress
I'll add it to the Readme file. Thanks.

**Comment by scott2b** [comment]
got it. Thanks
